- name: register and ignore_errors example
  hosts: all
  vars:
    path: "/etc"
  tasks:
    - debug:
        msg: "test OK!!"
      when: path is directory
    - shell: useradd test
      register: useradd
      ignore_errors: true
    - debug:
        msg: "useradd faild!!"
      when: useradd.rc != 0