- name: var example, gather_facts no, and register example
  hosts: all
  gather_facts: no
  vars:
    path: "/opt/test2"
  tasks:
    - file:
        path: "{{ path }}"
        state: touch
      register: file_task
    - debug:
        msg: "touch success!!"
      when: file_task is success