- name: with_dict 循环子选项
  gather_facts: no
  vars: 
    users: 
      manager:
        name: admin
        uid: 2000
        shell: /bin/bash
      common:
        name: guest
        uid: 4000
        shell: /bin/bash
  hosts: all
  tasks: 
    - debug:
        msg: "exist users are: {{ item.value.name }}"
      with_dict: "{{ users }}"
  