- name: with_items 循环子选项:useradd
  gather_facts: no
  hosts: all
  vars: 
    users: 
      - name: user1
        id: 2000
        shell: /bin/bash
      - name: user2
        id: 2001
        shell: /sbin/nologin
      - name: user3
        id: 2002
        shell: /bin/false
  tasks: 
    - user:
        name: "{{ item.name }}"
        uid: "{{ item.id }}"
        shell: "{{ item.shell }}"
      with_items: "{{ users }}"
  